//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proactive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int codigo { get; set; }
        public int numero_cuenta { get; set; }
        public string nombre_cliente { get; set; }
        public int codigo_pais { get; set; }
        public int codigo_estado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
